package advance.store;

public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_ext.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_ext.queueId
     *
     * @mbggenerated
     */
    private Integer queueid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_ext.msgId
     *
     * @mbggenerated
     */
    private String msgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_ext.msg
     *
     * @mbggenerated
     */
    private String msg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_ext.id
     *
     * @return the value of message_ext.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_ext.id
     *
     * @param id the value for message_ext.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_ext.queueId
     *
     * @return the value of message_ext.queueId
     *
     * @mbggenerated
     */
    public Integer getQueueid() {
        return queueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_ext.queueId
     *
     * @param queueid the value for message_ext.queueId
     *
     * @mbggenerated
     */
    public void setQueueid(Integer queueid) {
        this.queueid = queueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_ext.msgId
     *
     * @return the value of message_ext.msgId
     *
     * @mbggenerated
     */
    public String getMsgid() {
        return msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_ext.msgId
     *
     * @param msgid the value for message_ext.msgId
     *
     * @mbggenerated
     */
    public void setMsgid(String msgid) {
        this.msgid = msgid == null ? null : msgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_ext.msg
     *
     * @return the value of message_ext.msg
     *
     * @mbggenerated
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_ext.msg
     *
     * @param msg the value for message_ext.msg
     *
     * @mbggenerated
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    @Override
    public String toString() {
        return "Message{" +
                "id=" + id +
                ", queueid=" + queueid +
                ", msgid='" + msgid + '\'' +
                ", msg='" + msg + '\'' +
                '}';
    }
}